server:
  port: ${SPRING_APPLICATION_PORT}

spring:
  config:
    import: optional:file:.env-local[.properties]
  datasource:
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driverClassName: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
  security:
    jwt:
      secret: ${JWT_SECRET}
      access: ${JWT_ACCESS}
      refresh: ${JWT_REFRESH}
  jpa:
    show-sql: ${SHOW_SQL}
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        javax.cache:
          provider: org.ehcache.jsr107.EhcacheCachingProvider
          uri: ehcache.xml
        cache:
          use_query_cache: true
          use_second_level_cache: true
          region.factory_class: jcache
  flyway:
    enabled: true

logging:
  level:
    web: ${LOGGING_WEB}
    org:
      springframework:
        security:
          web:
            context:
              HttpSessionSecurityContextRepository: ${LOGGING_HTTP_SESSION_SECURITY_CONTEXT_REPOSITORY}